### ISSUE TITLE
Allow default full/mini/nano loading behavior

### ISSUE THREAD

**Issue by GwJZant** [RaraProjects/metrics#1]
Would be useful to have the ability to have Metrics remember what your last visual mode was (or allow a setting to control) and load in that mode rather than always loading in full mode.

**Comment by RaraProjects** [comment]
Hey! I've thought about that and I can see how that is valuable. The main barrier to me doing that, at least in the past, is I'm worried that someone might get stuck if they don't know how to do the text commands to switch back to another mode. I could add buttons to mini/nano to switch back but then it goes against the "smallness" of the window. One way around these might be to make a toggle where you can opt-in to Metrics remembering which parse mode you were last in. Do you think a setting like that would meet your need? Or you can tell me that I'm totally overthinking the getting stuck thing.

**Comment by RaraProjects** [comment]
I've been thinking about this and I have an idea of how I want to do it. I'll work on it!

**Comment by RaraProjects** [comment]
This is done and on the Testing branch. I'll push it to the Released branch after some field testing.

**Comment by GwJZant** [comment]
Yeah I think a toggle in settings would be perfect actually. Can keep it to
default to NOT remember and just enable that to let it remember

**Comment by RaraProjects** [comment]
I released this today. I elected to forgo the opt-in option. It remembers automatically. I made the help text (/met) more robust to address the concern of anyone getting stuck.
