### ISSUE TITLE
parse not showing

### ISSUE THREAD

**Issue by Cannon1210** [RaraProjects/metrics#2]
at first the parse showed up fine.  i then went to settings and tried to adjust the transparency and when i cleared the field, the whole parse menu disappeared.  is it possible that its so transparent i can no longer see it? or is the menu just gone?  i have no idea how to pull it back up.

**Comment by Prongles4** [comment]
Same issue as Cannon1210. I tried to adjust transparency and now I can't see anything at all on metrics.

**Comment by RaraProjects** [comment]
I was able to recreate the same thing. I'll add some checks to prevent this from happening, and here's what you can do to fix it now.

Steps to Fix:
1. Unload Metrics.
2. With Metrics unloaded, go to your Horizon addon config folder settings for Metrics. For example, mine is HorizonXI/Game/config/addons/Metrics/CharacterName. You should see files called blog, focus, parse, etc.
4. Delete the file called "window".
5. Reload Metrics.
6. Your window should now be set to the default transparency.

Steps to Recreate (for reference):
1. Load Metrics.
2. Go to the Settings tab.
3. Go to the GUI sub-tab.
4. Ctrl-Click on Window Transparency.
7. Press 0.
8. The window's transparency will change to zero making it completely invisible.

**Comment by Prongles4** [comment]
This fix worked for me! Thanks!

**Comment by RaraProjects** [comment]
I released the guard rails today so this issue shouldn't be able to happen anymore (at least with the workflow I outlined in post #3).
