### ISSUE TITLE
Random Bug (table index is nil)

### ISSUE THREAD

**Issue by ayechonk** [RaraProjects/metrics#4]
I outpost wrapped into Qufim and got that error
![image](https://github.com/RaraProjects/metrics/assets/12193663/f8108a5e-5ddd-4ad6-8e30-7501ada61868)

**Comment by RaraProjects** [comment]
Hey ayechonk, thanks for posting this. Preventing crashes is a priority of mine. Which version are you using? I checked line 18 for dps.lua and it isn't a table reference anymore, so I'm wondering if you're using an older version.

**Comment by ayechonk** [comment]
Sorry I'm just now seeing this. Feel free to close it as I dont think i've seen it in a while.
