### ISSUE TITLE
Feature Request: Separate Settings Window

### ISSUE THREAD

**Issue by jimmy58663** [RaraProjects/metrics#5]
Request that all the settings be moved into a separate Imgui window. Currently hitting the Settings button expands everything downwards which can knock some stuff off the screen. Settings could be moved to a separate window and accessed by a command such as /metrics, /metrics config, /metrics settings, or /metrics editor (not all 4 are needed).

**Comment by RaraProjects** [comment]
I've got a multi window mode available on the testing branch that uses this paradigm. I want to push it out to the release branch soon, but I want to field test a couple things for a bit longer.

**Comment by RaraProjects** [comment]
Separate settings windows are available now!
