### ISSUE TITLE
Feature Request: Reset button

### ISSUE THREAD

**Issue by jimmy58663** [RaraProjects/metrics#8]
Request a button be added to reset the parse data. Icons from FontAwesome free tier can be used as they are incorporated in Ashita. I was not sure how to call them from Ashita, but you can use the unicode characters that are listed [here](https://github.com/AshitaXI/Ashita-v4beta/blob/main/plugins/sdk/ImGuiFontAwesome.h#L6130).

Additional buttons for reporting might be nice to have as well.

**Comment by RaraProjects** [comment]
Reset button is available now.
