### ISSUE TITLE
Feature Request: Additional Settings

### ISSUE THREAD

**Issue by jimmy58663** [RaraProjects/metrics#9]
Request additional settings for:

- Font scaling
    - imgui.SetWindowFontScale([setting for font scale])
- Window Opacity
    - imgui.SetNextWindowBgAlpha([setting for opacity])

**Comment by RaraProjects** [comment]
Scaling and Alpha settings are available in the GUI tab of Settings. Are you requesting something else in addition to those?

**Comment by jimmy58663** [comment]
Nope, just totally missed those. Can close this then.

**Comment by RaraProjects** [comment]
No problem. Thanks for the comment. :)
